name: Rust Release build

on:
  push:
    tags:
      - "*"

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    name: Build and Release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: mod_jar_inspector
            asset_name: mod_jar_inspector_linux_amd64
          - os: macos-latest
            artifact_name: mod_jar_inspector
            asset_name: mod_jar_inspector_macos_amd64
          - os: windows-latest
            artifact_name: mod_jar_inspector.exe
            asset_name: mod_jar_inspector_windows_amd64.exe
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build project
        run: cargo build --release
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@2.1.0
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/release/${{ matrix.artifact_name }}
          asset_name: ${{ matrix.asset_name }}
          tag: ${{ github.ref }}
